/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "OS_MCAL_interface.h"
#include "main.h"




int main(void)
{
	enable_system_faults();

	STK_init(1000);

	Stack_Schedular_Stack_init(SCHED_STACK_START);

	init_tasks_stack();

	change_to_PSP();

	task1_handler();

	/* Loop forever */
	for (;;);
}


void task1_handler(void)
{
	while (1)
	{

	}
}
void task2_handler(void)
{
	while (1)
	{

	}
}
void task3_handler(void)
{
	while (1)
	{

	}
}
void task4_handler(void)
{
	while (1)
	{

	}
}
